# standard jekyll configuration

permalink: /:categories/:title/
highlighter:  pygments
markdown: rdiscount
exclude: ['readme.md', 'Procfile', 'config.rb', '.gitignore', '.sass-cache', 'Gemfile', 'Gemfile.lock']
show_drafts: false

title: Take Back the Archive 
baseurl: http://clioweb.github.io/takeback
